# action.yml
name: setup-docker
description: 'setup docker'

runs:
  using: 'composite'
  steps:
    - shell: bash
      name: create cache
      run: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update -qq
        apt-get  -q install -qq \
          containerd.io \
          docker-ce \
          docker-ce-cli \
          ;

    - shell: bash
      run: docker info
