apiVersion: v2
name: forgejo
description: Forgejo Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: 9.0.2
icon: https://code.forgejo.org/forgejo/forgejo/raw/branch/forgejo/assets/logo.svg
home: https://forgejo.org/

keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - forgejo
  - gitea
  - gogs
sources:
  - https://code.forgejo.org/forgejo-helm/forgejo-helm
  - https://codeberg.org/forgejo/forgejo
maintainers:
  - name: Michael Kriese
    email: michael.kriese@visualon.de

# Bitnami charts are served from Docker Hub
# https://hub.docker.com/u/bitnamicharts
# https://blog.bitnami.com/2023/01/bitnami-helm-charts-available-as-oci.html
dependencies:
  # https://github.com/bitnami/charts/blob/main/bitnami/common/Chart.yaml
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.27.0
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.5.38
    condition: postgresql.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/Chart.yaml
  - name: postgresql-ha
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.3.9
    condition: postgresql-ha.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/Chart.yaml
  - name: redis-cluster
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.0.8
    condition: redis-cluster.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 20.3.0
    condition: redis.enabled
