apiVersion: v2
name: forgejo
description: Forgejo Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: 1.18.5-0
icon: https://design.codeberg.org/logo-kit/icon.svg
home: https://forgejo.org/

keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - forgejo
  - gitea
  - gogs
sources:
  - https://codeberg.org/forgejo-contrib/forgejo-helm
  - https://codeberg.org/forgejo/forgejo
maintainers:
  - name: Michael Kriese
    email: michael.kriese@visualon.de

# Bitnami charts are served from GitHub CDN - See https://github.com/bitnami/charts/issues/10833 for details
dependencies:
- name: memcached
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 6.3.12
  condition: memcached.enabled
- name: mysql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 9.5.2
  condition: mysql.enabled
- name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 12.2.3
  condition: postgresql.enabled
- name: mariadb
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 11.5.3
  condition: mariadb.enabled
