apiVersion: v2
name: forgejo
description: Forgejo Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: 1.19.0-2
icon: https://design.codeberg.org/logo-kit/icon.svg
home: https://forgejo.org/

keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - forgejo
  - gitea
  - gogs
sources:
  - https://codeberg.org/forgejo-contrib/forgejo-helm
  - https://codeberg.org/forgejo/forgejo
maintainers:
  - name: Michael Kriese
    email: michael.kriese@visualon.de

# Bitnami charts are served from Docker Hub
# https://hub.docker.com/u/bitnamicharts
# https://blog.bitnami.com/2023/01/bitnami-helm-charts-available-as-oci.html

dependencies:
- name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 6.3.13
  condition: memcached.enabled
- name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 9.7.0
  condition: mysql.enabled
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.2.6
  condition: postgresql.enabled
- name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 11.5.5
  condition: mariadb.enabled
