apiVersion: v2
name: forgejo
description: Forgejo Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: 12.0.0
icon: https://code.forgejo.org/forgejo/forgejo/raw/branch/forgejo/assets/logo.svg
home: https://forgejo.org/

keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - forgejo
  - gitea
  - gogs
sources:
  - https://code.forgejo.org/forgejo-helm/forgejo-helm
  - https://codeberg.org/forgejo/forgejo
maintainers:
  - name: Michael Kriese
    email: michael.kriese@visualon.de

# Bitnami charts are served from ghcr mirror because of rate limiting on Docker Hub
# https://hub.docker.com/u/bitnamicharts
# https://blog.bitnami.com/2023/01/bitnami-helm-charts-available-as-oci.html
# https://github.com/bitnami/charts/issues/30853
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
dependencies:
  # https://github.com/bitnami/charts/blob/main/bitnami/common/Chart.yaml
  - name: common
    repository: oci://ghcr.io/visualon/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.3
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml
  - name: postgresql
    repository: oci://ghcr.io/visualon/bitnamicharts
    version: 16.7.20
    condition: postgresql.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/Chart.yaml
  - name: postgresql-ha
    repository: oci://ghcr.io/visualon/bitnamicharts
    version: 16.0.22
    condition: postgresql-ha.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/valkey-cluster/Chart.yaml
  - name: valkey-cluster
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 3.0.18
    condition: valkey-cluster.enabled
  # https://github.com/bitnami/charts/blob/main/bitnami/valkey/Chart.yaml
  - name: valkey
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 3.0.22
    condition: valkey.enabled
