# action.yml
name: setup-node
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: .node-version
        # cache: 'npm'
    - shell: bash
      run: corepack enable
    - shell: bash
      run: pnpm install --frozen-lockfile
