# action.yml
name: setup-node
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6
      with:
        standalone: true

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: .node-version
        cache: 'pnpm'

    - shell: bash
      run: pnpm install --frozen-lockfile
