# action.yml
name: setup-node
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: .node-version
        cache: 'npm'
    - shell: bash
      run: npm ci
