# action.yml
name: setup-node
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .node-version
        # cache: 'npm'
    - shell: bash
      run: corepack enable
    - shell: bash
      run: pnpm install --frozen-lockfile
