# action.yml
name: setup-node
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: .node-version
        # cache: 'npm'
    - shell: bash
      run: corepack enable
    - shell: bash
      run: pnpm install --frozen-lockfile
