suite: config template | cache config
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: cache is configured correctly for 'memory'
    template: templates/gitea/config.yaml
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.cache
          value: |-
            ADAPTER=memory
            HOST=

  - it: cache can be customized
    template: templates/gitea/config.yaml
    set:
      forgejo.config.cache.ADAPTER: custom-adapter
      forgejo.config.cache.HOST: custom-host
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.cache
          value: |-
            ADAPTER=custom-adapter
            HOST=custom-host
