suite: config template | session config
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: session is configured correctly for 'memory'
    template: templates/gitea/config.yaml
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.session
          value: |-
            PROVIDER=memory
            PROVIDER_CONFIG=

  - it: session can be customized
    template: templates/gitea/config.yaml
    set:
      forgejo.config.session.PROVIDER: custom-provider
      forgejo.config.session.PROVIDER_CONFIG: custom-provider-config
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.session
          value: |-
            PROVIDER=custom-provider
            PROVIDER_CONFIG=custom-provider-config
