# default values with some modifications

# Use mirror
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
global:
  security:
    allowInsecureImages: true
redis-cluster:
  image:
    registry: public.ecr.aws
postgresql-ha:
  postgresql:
    image:
      registry: ghcr.io/visualon
  pgpool:
    image:
      registry: ghcr.io/visualon
test:
  image:
    name: code.forgejo.org/oci/busybox
