# default values with some modifications

# Use mirror
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
global:
  security:
    allowInsecureImages: true
valkey-cluster:
  image:
    registry: public.ecr.aws
test:
  image:
    name: code.forgejo.org/oci/busybox
