# Test codeberg.org image
image:
  registry: codeberg.org
# Use mirror
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
test:
  image:
    name: code.forgejo.org/oci/busybox

valkey-cluster:
  enabled: false

persistence:
  enabled: false

forgejo:
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
