redis-cluster:
  enabled: false
postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  # Use mirror
  # https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
  global:
    imageRegistry: public.ecr.aws
    security:
      allowInsecureImages: true

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
