valkey-cluster:
  enabled: false

valkey:
  enabled: true

global:
  security:
    allowInsecureImages: true

# Use mirror
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
test:
  image:
    name: code.forgejo.org/oci/busybox

persistence:
  enabled: true

gitea:
  config:
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
