redis-cluster:
  enabled: false
postgresql-ha:
  enabled: false

redis:
  enabled: true
  # Use mirror
  # https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
  image:
    registry: public.ecr.aws

postgresql:
  enabled: true
  # Use mirror
  # https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
  image:
    registry: ghcr.io/visualon
global:
  security:
    allowInsecureImages: true

# Use mirror
# https://code.forgejo.org/forgejo-helm/forgejo-helm/issues/1045
test:
  image:
    name: code.forgejo.org/oci/busybox

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
