image:
  registry: codeberg.org
  repository: forgejo-experimental/forgejo
  tag: 7.0-test@sha256:b138ce55ef61ff9c257accab53bd7fc9e27448aa9c031a6a8f9ef9aa775424df
  rootless: false # rootless doesn't work with tag with digest

redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
