image:
  registry: codeberg.org
  repository: forgejo-experimental/forgejo
  tag: 8.0-test@sha256:bd34106d6b15577ac6b7b5c4259fc44c80fe2569d5bd8078b36edaff75520912

redis-cluster:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
