image:
  registry: codeberg.org
  repository: forgejo-experimental/forgejo
  tag: 8.0-test@sha256:53a7c227c5e8a315cbbbb035647275beda70da2eb412a5e6b646cabae420d498
  rootless: false # rootless doesn't work with tag with digest

redis-cluster:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
