image:
  registry: codeberg.org
  repository: forgejo-experimental/forgejo
  tag: 9.0-test@sha256:2c44de40b83f5f65e5f7759a83f09226076fbbc26a2b4b33543721f2274c3083

redis-cluster:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
