{{- if .Values.httpRoute.enabled -}}
{{- include "forgejo.compat" . -}}
{{- $fullName := include "gitea.fullname" . -}}
{{- $httpRoute := .Values.httpRoute }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  {{- with $httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $httpRoute.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
  - matches:
    {{- with $httpRoute.matches.path }}
    - path:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $httpRoute.matches.timeouts }}
    timeouts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    backendRefs:
    - kind: Service
      name: {{ $fullName }}-http
      port: {{ .Values.service.http.port }}
    {{- with $httpRoute.filters }}
    filters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
