platform: linux/amd64

when:
  event:
    - pull_request
    - push
    - tag
  branch:
    - main
    - release/**

services:
  docker:
    image: docker:24.0.7-dind
    pull: true
    environment:
      DOCKER_TLS_CERTDIR: ''

matrix:
  k8s:
    # from https://hub.docker.com/r/kindest/node/tags
    #    - v1.25.3 # renovate: kindest
    - v1.28.0 # renovate: kindest

pipeline:
  create-cluster:
    image: alpine:3.18.5
    pull: true
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - apk add docker-cli kind
      - export KUBECONFIG=$${CI_WORKSPACE}/kube.config
      - sleep 15s
      - docker info
      - kind create cluster --config e2e/kind.cluster.yml --image kindest/node:${k8s} --wait 1m
      - kind get clusters
      - docker ps
      # replace localhost or 0.0.0.0 in the kubeconfig file with "docker", in order to be able to reach the cluster through the docker service
      - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' $${KUBECONFIG}

  ct-install:
    image: quay.io/helmpack/chart-testing:v3.10.1
    pull: true
    commands:
      - git fetch --no-tags --filter=blob:none origin
      - export KUBECONFIG=$${CI_WORKSPACE}/kube.config
      - kubectl get no -o wide
      - ct install --config tools/ct.yml --charts .
