platform: linux/amd64

when:
  event:
    - pull_request
    - tag
    - push
  branch:
    - main
    - release/**

pipeline:
  deps:
    image: alpine:3.17.1
    pull: true
    commands:
      - apk add --no-cache helm
      - helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      - helm dependency build

  helm-lint:
    image: alpine:3.17.1
    pull: true
    commands:
      - apk add --no-cache helm
      - helm lint

  helm-template:
    image: alpine:3.17.1
    pull: true
    commands:
      - apk add --no-cache helm
      - helm template --debug gitea-helm .

  verify-readme:
    image: alpine:3.17.1
    pull: true
    commands:
      - apk add --no-cache make nodejs npm git
      - make readme
      - git diff --exit-code --name-only README.md
