platform: linux/amd64

when:
  branch:
    exclude:
      - pages

pipeline:
  helm-lint:
    image: alpine:3.17
    pull: true
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - helm dependency build
      - helm lint

  helm-template:
    image: alpine:3.17
    pull: true
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - helm template --debug gitea-helm .

  verify-readme:
    image: alpine:3.17
    pull: true
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing make npm git
      - make readme
      - git diff --exit-code --name-only README.md
