platform: linux/amd64

when:
  event:
    - pull_request
    - tag
    - push
  branch:
    - main
    - release/**

pipeline:
  deps:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add helm
      - helm dependency build

  helm-lint:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add helm
      - helm lint

  helm-template:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add helm
      - helm template --debug gitea-helm .

  helm-unittests:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add make helm git bash
      - helm plugin install --version v0.3.6 https://github.com/helm-unittest/helm-unittest
      - helm dependency update
      - make unittests

  verify-readme:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add make nodejs npm git
      - make readme
      - git diff --exit-code --name-only README.md

  yaml-lint:
    image: alpine:3.18.4
    pull: true
    commands:
      - apk add yamllint
      - yamllint -f colored .
