platform: linux/amd64

depends_on:
  - lint

when:
  event:
    - tag
  tag: v*

pipeline:
  generate-chart:
    image: alpine:3.17.0
    pull: true
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - apk add --no-cache git npm
      - helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      - helm dependency build
      - rm -rf tmp/
      - helm package --version "${CI_COMMIT_TAG##v}" -d tmp/ ./
      - npm ci
      - npm run changelog "${CI_COMMIT_TAG##v}" tmp/changelog.md
    secrets:
      - token

  publish-release:
    image: plugins/gitea-release
    pull: true
    settings:
      base_url: https://codeberg.org
      api_key:
        from_secret: token
      files: tmp/*
      title: ${CI_COMMIT_TAG##v}
      file_exists: fail
      note: tmp/changelog.md

  publish-chart:
    image: alpine:3.17.0
    pull: true
    commands:
      - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
      - echo $${TOKEN} | helm registry login -u viceice --password-stdin codeberg.org/forgejo-contrib
      - helm push tmp/forgejo-${CI_COMMIT_TAG##v}.tgz oci://codeberg.org/forgejo-contrib
    secrets:
      - token
