platform: linux/amd64

depends_on:
  - lint

when:
  event:
    - tag
  tag: v*

pipeline:
  generate-chart:
    image: alpine:3.17.3
    pull: true
    commands:
      - apk add git nodejs npm helm
      - helm dependency build
      - rm -rf tmp/
      - helm package --version "${CI_COMMIT_TAG##v}" -d tmp/ ./
      - npm ci
      - npm run changelog "${CI_COMMIT_TAG##v}" tmp/changelog.md
    secrets:
      - token

  publish-release:
    image: codeberg.org/woodpecker-plugins/gitea-release:0.2.0
    pull: true
    settings:
      base_url: https://codeberg.org
      api_key:
        from_secret: token
      files: tmp/*.tgz
      title: ${CI_COMMIT_TAG##v}
      file_exists: fail
      note: tmp/changelog.md

  publish-chart:
    image: alpine:3.17.3
    pull: true
    commands:
      - apk add helm
      - echo $${TOKEN} | helm registry login -u viceice --password-stdin codeberg.org/forgejo-contrib
      - helm push tmp/forgejo-${CI_COMMIT_TAG##v}.tgz oci://codeberg.org/forgejo-contrib
    secrets:
      - token
