platform: linux/amd64

when:
  event:
    - cron

pipeline:
  renovate:
    image: ghcr.io/visualon/renovate:34.154.1
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      LOG_LEVEL: debug
    secrets:
      - source: token
        target: renovate_token
      - source: gh_token
        target: github_com_token
    when:
      - event:
          - cron
        cron: renovate
